name: Lint Check Every Commit

on:
  push:
    branches:
      - main

jobs:
  check-lint:
    name: Lint Check Commit
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: install dependencies
        run: npm install

      - name: run lint check
        run: npm run lint
